[book]
authors = ["Lane Kolbly"]
language = "en"
multilingual = false
src = "src"
title = "Ripstop HDL"

[preprocessor]

[preprocessor.wavedrom]
command = "mdbook-wavedrom"

[output]

[output.html]
additional-js = ["wavedrom.min.js", "wavedrome-default.js"]
